### ISSUE TITLE
Emotion does not pick autoLabel config from babelrc

### ISSUE THREAD

**Issue by tkivela** [osdevisnot/react-app-rewire-contrib#9]
Symptom: If autoLabel (https://github.com/emotion-js/emotion/tree/master/packages/babel-plugin-emotion#autolabel) is configured to be true in .babelrc the generated class names do not include the name of variable.

Simple example to reproduce this behaviour: https://github.com/tkivela/cerebraltemplate

**Comment by osdevisnot** [comment]
Hi @tkivela It seems I missed this notification. When I look at tkivela/cerebraltemplate now, it seems this repo is not using these rewires anymore.
